[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
FerriteViz = "59d0093e-b1f1-4fb7-ac85-ab57e45f39d9"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
